name: Darien R Mosaics
favicon: null
layout_spectrum: 0.14229361759498715
typography_spectrum: 0
title: 'Darien R Mosaics '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73939835-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e36b0a'
    - '#00af52'
    - '#fe0002'
    - '#000000'
  brandStrength: 0.36696852766908705
  lightness: 0.4842837306205183
  saturation: 0.41375547321513295
  rhythmicContrast: 0.4437926970422268
purpose: []
