name: Darien R Mosaics
favicon: null
layout_spectrum: 0.14229361759498715
typography_spectrum: 0.17739061801694334
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.36696852766908705
  lightness: 0.4842837306205183
  saturation: 0.41375547321513295
  rhythmicContrast: 0.4437926970422268
purpose: []
